#!/usr/bin/env bash
#
# Builds the BMP conformance corpus the test suite cannot build for itself.
#
# BMP is not one format. It is a family: BITMAPCOREHEADER through BITMAPV5HEADER, BI_RGB /
# RLE4 / RLE8 / BITFIELDS / JPEG / PNG / CMYK, 1 to 64 bits per pixel, top-down and
# bottom-up, palettes that may be absent or offset, and `bfOffBits` values that may be zero.
# Writing a generator for that by hand would be writing a second BMP implementation to test
# the first one with.
#
# So this fetches Jason Summers' BMP Suite and runs its own generator. Reaching for a
# conformance suite rather than hand-rolled fixtures is the same judgement `archive-formats`
# arrived at four times: the defects in a format reader are the ones only an adversarial
# input exposes, and `b/` and `q/` below are ninety-one such inputs somebody else already
# thought of.
#
# Licensing, which is why this is a script and not committed data:
#
#   - The generator (`bmpsuite.c`) is GPL-3.0-or-later. This project is Apache-2.0 and its
#     `deny.toml` allow-list carries no GPL term — the same bar that ruled out `unrar-rs`
#     0.5.5 in Change 2. Running a GPL program is unrestricted (GPL-3.0 §2); *conveying* one
#     is what carries obligations. This script therefore runs it and never redistributes it,
#     exactly as `make-rar-fixtures.sh` runs RARLAB's proprietary `rar` without shipping it.
#   - The generated images are explicitly NOT covered by that licence and are public domain,
#     stated by the author in `readme.txt`: "Image files generated by this program are not
#     covered by this license, and are in the public domain (except for the embedded ICC
#     profiles)."
#   - Two files are that exception: `q/rgb24prof.bmp` and `q/rgb24prof2.bmp` embed an ICC
#     profile the readme excludes. Measured — they are the only two in all ninety-one. This
#     script deletes them, so nothing under `tools/` carries a licence this repository has
#     not cleared. Colour management is out of scope for the Slice anyway, so nothing is
#     lost by their absence.
#
# Everything lands under `tools/`, which is gitignored. CI never runs this; tests that need
# the corpus skip with a message naming this script when it is absent.
#
# Usage:
#   tests/fixtures/make-bmp-fixtures.sh            # fetch and build
#   CAR_BMP_FIXTURES=/somewhere tests/fixtures/make-bmp-fixtures.sh
#
# Prerequisites: `git`, `make`, and a C compiler — all of which this repository already
# requires, because `mozjpeg-sys` builds mozjpeg from source on every clean build.

set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
tools="$root/tools"
checkout="$tools/bmpsuite"
out="${CAR_BMP_FIXTURES:-$tools/bmp-fixtures}"

# 2.8, the release current when this script was written. Pinned by tag rather than floating
# so a fixture that stops reproducing points at a change here rather than upstream.
suite_version="2.8"

# The two files whose embedded ICC profiles the upstream readme excludes from the public
# domain. Named individually rather than matched by pattern: the list is short, it is
# verified below, and a pattern would silently start or stop covering a file.
icc_bearing=("q/rgb24prof.bmp" "q/rgb24prof2.bmp")

die() { printf '%s: %s\n' "${BASH_SOURCE[0]##*/}" "$1" >&2; exit 1; }
step() { printf '\n== %s\n' "$1"; }

for tool in git make cc; do
    command -v "$tool" >/dev/null 2>&1 || die "missing $tool; see the prerequisites above"
done

# ---------------------------------------------------------------- the generator

if [ -d "$checkout/.git" ]; then
    step "updating $checkout"
    git -C "$checkout" fetch --tags --quiet
else
    step "cloning bmpsuite into $checkout"
    mkdir -p "$tools"
    git clone --quiet https://github.com/jsummers/bmpsuite.git "$checkout"
fi

# The tag if upstream has one for this version, otherwise the default branch with the
# version asserted from `readme.txt`. Upstream has not always tagged its releases, and a
# silent fall back to whatever `master` happens to be is how a corpus stops being pinned.
if git -C "$checkout" rev-parse --verify --quiet "refs/tags/v$suite_version" >/dev/null; then
    git -C "$checkout" -c advice.detachedHead=false checkout --quiet "v$suite_version"
    printf 'bmpsuite: tag v%s\n' "$suite_version"
else
    git -C "$checkout" checkout --quiet master
    git -C "$checkout" pull --quiet --ff-only
    stated="$(sed -n 's/^Version \(.*\)$/\1/p' "$checkout/readme.txt" | head -1)"
    [ "$stated" = "$suite_version" ] || die \
        "upstream has no v$suite_version tag and master states version '$stated'; update suite_version here after reading what changed"
    printf 'bmpsuite: master, readme states version %s\n' "$stated"
fi

# ---------------------------------------------------------------- the corpus

step "generating"
make -C "$checkout" --silent
make -C "$checkout" --silent check >/dev/null || die "upstream's own checksum check failed"
printf 'checksums: OK (upstream `make check`)\n'

rm -rf "$out"
mkdir -p "$out"
for dir in g q b x; do
    [ -d "$checkout/$dir" ] || die "generated no $dir/ directory"
    cp -R "$checkout/$dir" "$out/$dir"
done

step "removing the ICC-bearing files"
for file in "${icc_bearing[@]}"; do
    [ -f "$out/$file" ] || die "expected $file to exist before removing it; check the upstream version"
    rm -f "$out/$file"
    printf 'removed %s\n' "$file"
done

# The check that the exclusion above is complete rather than a list somebody once wrote.
# `acsp` is the ICC profile signature at byte 36 of every profile header, so a BMP carrying
# one contains it. If this fires, upstream added a profile-bearing file and the list needs
# extending — do not silence it.
step "verifying no profile-bearing file remains"
remaining="$(grep -rla 'acsp' "$out" || true)"
[ -z "$remaining" ] || die "these still embed an ICC profile: $remaining"
printf 'none\n'

# ---------------------------------------------------------------- what was produced

step "corpus at $out"
for dir in g q b x; do
    printf '%s/: %s files\n' "$dir" "$(find "$out/$dir" -name '*.bmp' | wc -l | tr -d ' ')"
done
cat <<'EOF'

  g/ good         — a reader claiming BMP support must read every one
  q/ questionable — unusual, obsolete, or arguably invalid; a reader may refuse one, by name
  b/ bad          — clearly invalid; a reader must refuse without crashing
  x/ related      — not BMP; must not be mistaken for one

Upstream's per-file descriptions: tools/bmpsuite/html/bmpsuite.html
EOF
